# These two are required
db_path = "data.db"
asset_storage = "user_assets"

# 32 bytes of random data
csrf_key = "CHANGE ME"

# This is optional to make development easier
[cals]
# ICS links for calendars
second_floor = "https://calendar.google.com/calendar/ical/SOMETHING%40group.calendar.google.com/public/basic.ics"
green_room = ""
purple_room = ""
events = ""
